
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-dining-s26-08
owner: ucsb-cs156-s26
repo_name: proj-dining-s26-08
pull_requests: [{"author":{"id":"U_kgDOCVPcVQ","is_bot":false,"login":"matthewli10","name":""},"headRefName":"matthewli-fix-star-ratings","number":50,"title":"Fix: Star ratings from approved reviews now display on the main menu","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-08/pull/50"},{"author":{"id":"U_kgDODgRftg","is_bot":false,"login":"CMWENDY","name":"Wendy Contreras"},"headRefName":"wc-statistics-commons-averages","number":48,"title":"Add Dining Commons Averages statistics pages","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-08/pull/48"},{"author":{"id":"U_kgDODgRftg","is_bot":false,"login":"CMWENDY","name":"Wendy Contreras"},"headRefName":"wc-statistics-overview","number":46,"title":"Add Statistics overview page and navbar dropdown","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-08/pull/46"},{"author":{"id":"U_kgDOCVHSBA","is_bot":false,"login":"dev-anj","name":"Anjali Dev"},"headRefName":"adev-issue16-reviewform-rhf","number":36,"title":"Adev issue16 reviewform rhf","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-08/pull/36"},{"author":{"id":"U_kgDOCVHSBA","is_bot":false,"login":"dev-anj","name":"Anjali Dev"},"headRefName":"adev-issue2-replace-hrefs","number":29,"title":"Replace internal hrefs with React Router Link in AppNavbar","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-08/pull/29"}]
