
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-dining-s26-08
owner: ucsb-cs156-s26
repo_name: proj-dining-s26-08
pull_requests: [{"author":{"id":"U_kgDOCWXSsA","is_bot":false,"login":"ccabacungan","name":""},"headRefName":"ccabacungan/moderator-create-page","number":30,"title":"Add moderator create page","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-08/pull/30"},{"author":{"id":"U_kgDOCVHSBA","is_bot":false,"login":"dev-anj","name":"Anjali Dev"},"headRefName":"adev-issue2-replace-hrefs","number":29,"title":"Replace internal hrefs with React Router Link in AppNavbar","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-08/pull/29"},{"author":{"id":"U_kgDOCVHlaQ","is_bot":false,"login":"riasingh455","name":""},"headRefName":"ria-integration-test","number":28,"title":"Ria integration test","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-08/pull/28"},{"author":{"id":"U_kgDOCWXSsA","is_bot":false,"login":"ccabacungan","name":""},"headRefName":"ccabacungan/moderation-page","number":27,"title":"Implement moderation page","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-08/pull/27"},{"author":{"id":"U_kgDODgRftg","is_bot":false,"login":"CMWENDY","name":"Wendy Contreras"},"headRefName":"wc-implement-review-edit-page","number":26,"title":"Implement Review Edit Page","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-08/pull/26"},{"author":{"id":"U_kgDOCVHlaQ","is_bot":false,"login":"riasingh455","name":""},"headRefName":"ria-add-moderator","number":24,"title":"add moderator","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-08/pull/24"},{"author":{"id":"U_kgDOCWXSsA","is_bot":false,"login":"ccabacungan","name":""},"headRefName":"ccabacungan-moderator-backend","number":23,"title":"Use role tables for user roles","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-08/pull/23"},{"author":{"id":"U_kgDODgRftg","is_bot":false,"login":"CMWENDY","name":"Wendy Contreras"},"headRefName":"wc-toggleable-user-roles-frontend","number":22,"title":"Add toggle buttons for User Roles","url":"https://github.com/ucsb-cs156-s26/proj-dining-s26-08/pull/22"}]
